services:

  sales-eventstore:
    container_name: sales-eventstore
    # image: eventstore/eventstore:23.10.1-jammy
    image: docker.kurrent.io/kurrent-latest/kurrentdb:latest
    environment:
      - KURRENTDB_CLUSTER_SIZE=1
      - KURRENTDB_RUN_PROJECTIONS=All
      - KURRENTDB_START_STANDARD_PROJECTIONS=true
      - KURRENTDB_NODE_PORT=2113
      - KURRENTDB_INSECURE=true
      - KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "4113:2113"
    volumes:
      - type: volume
        source: kurrentdb-volume-data
        target: /var/lib/kurrentdb
      - type: volume
        source: kurrentdb-volume-logs
        target: /var/log/kurrentdb
    networks:
      - brewup-network
    restart: unless-stopped

  sagas-mongodb:
    container_name: sagas-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - sagas-mongodb-data:/data/db
    networks:
      - brewup-network
    restart: unless-stopped

  sales-mongodb:
    container_name: sales-mongodb
    image: mongo:latest
    ports:
      - "37017:27017"
    volumes:
      - sales-mongodb-data:/data/db
    networks:
      - brewup-network
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.3-management-alpine
    ports:
      - "5672:5672"
      - "5552:5552"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_stream rabbitmq_stream_management &&
             docker-entrypoint.sh rabbitmq-server"
    networks:
      - brewup-network
    restart: unless-stopped

networks:
  brewup-network:
    driver: bridge

volumes:
  kurrentdb-volume-data:
  kurrentdb-volume-logs:
  sagas-mongodb-data:
  sales-mongodb-data:
